INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('Andres', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-01', '');
INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('John', 'Doe', 'john.doe@gmail.com', '2017-08-02', '');
INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2017-08-03', '');
INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('Jane', 'Doe', 'jane.doe@gmail.com', '2017-08-04', '');
INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2017-08-05', '');
INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('Erich', 'Gamma', 'erich.gamma@gmail.com', '2017-08-06', '');
INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('Richard', 'Helm', 'richard.helm@gmail.com', '2017-08-07', '');
-- INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2017-08-08', '');
-- INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('John', 'Vlissides', 'john.vlissides@gmail.com', '2017-08-09', '');
-- INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('James', 'Gosling', 'james.gosling@gmail.com', '2017-08-010', '');
-- INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('Bruce', 'Lee', 'bruce.lee@gmail.com', '2017-08-11', '');
-- INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('Johnny', 'Doe', 'johnny.doe@gmail.com', '2017-08-12', '');
-- INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('John', 'Roe', 'john.roe@gmail.com', '2017-08-13', '');
-- INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('Jane', 'Roe', 'jane.roe@gmail.com', '2017-08-14', '');
-- INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('Richard', 'Doe', 'richard.doe@gmail.com', '2017-08-15', '');
-- INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('Janie', 'Doe', 'janie.doe@gmail.com', '2017-08-16', '');
-- INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('Phillip', 'Webb', 'phillip.webb@gmail.com', '2017-08-17', '');
-- INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('Stephane', 'Nicoll', 'stephane.nicoll@gmail.com', '2017-08-18', '');
-- INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('Sam', 'Brannen', 'sam.brannen@gmail.com', '2017-08-19', '');  
-- INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('Juergen', 'Hoeller', 'juergen.Hoeller@gmail.com', '2017-08-20', ''); 
-- INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('Janie', 'Roe', 'janie.roe@gmail.com', '2017-08-21', '');
-- INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('John', 'Smith', 'john.smith@gmail.com', '2017-08-22', '');
-- INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('Joe', 'Bloggs', 'joe.bloggs@gmail.com', '2017-08-23', '');
-- INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('John', 'Stiles', 'john.stiles@gmail.com', '2017-08-24', '');
-- INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('Richard', 'Roe', 'stiles.roe@gmail.com', '2017-08-25', '');
-- INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('Phillips', 'Webb', 'phillip.webb@gmail.com', '2017-08-17', '');
-- INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('Stephan', 'Nicoll', 'stephane.nicoll@gmail.com', '2017-08-18', '');
-- INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('Samuel', 'Brannen', 'sam.brannen@gmail.com', '2017-08-19', '');  
-- INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('James', 'Hoeller', 'juergen.Hoeller@gmail.com', '2017-08-20', ''); 
-- INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('Julian', 'Roe', 'janie.roe@gmail.com', '2017-08-21', '');
-- INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('David', 'Smith', 'john.smith@gmail.com', '2017-08-22', '');
-- INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('Richard', 'Bloggs', 'joe.bloggs@gmail.com', '2017-08-23', '');
-- INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('Mark', 'Stiles', 'john.stiles@gmail.com', '2017-08-24', '');
-- INSERT INTO clients (client_name, last_name, email, create_at, photo) VALUES('Lucas', 'Roe', 'stiles.roe@gmail.com', '2017-08-25', '');

INSERT INTO products (name, price, create_at) VALUES ("Smart TV Noblex DK65X6500 LED 4K 65 220V",186999,NOW());
INSERT INTO products (name, price, create_at) VALUES ("Smart Tv Noblex Dk43x7100pi Led 43'' Full Hd Con Android Tv",71999,NOW());
INSERT INTO products (name, price, create_at) VALUES ("Smart TV Samsung Series 5 UN43T5300AGCZB LED Full HD 43 220V - 240V",83999,NOW());
INSERT INTO products (name, price, create_at) VALUES ("Smart Tv LG 32 Pulgadas 32lq630bpsa Wifi Bluetooth Thinq Ai",69999,NOW());
INSERT INTO products (name, price, create_at) VALUES ("Apple iPhone 11 (256 GB) - Negro",320000,NOW());
INSERT INTO products (name, price, create_at) VALUES ("Apple iPhone 11 (128 GB) - Negro",251799,NOW());
INSERT INTO products (name, price, create_at) VALUES ("Samsung Galaxy S20 FE 5G 128 GB cloud red 6 GB RAM",183960,NOW());
